### ISSUE TITLE
[Bug] Synapse graph compilation failure (synStatus 26) with hybrid GDN models on v0.26.0

### ISSUE THREAD

**Issue by biondogs** [vllm-project/vllm-gaudi#1734]
## Bug Description

vllm-gaudi v0.26.0 fails with a Synapse graph compilation error on the first inference request when serving hybrid GDN (GatedDeltaNet) + FullAttention models. The same model and configuration works correctly on v0.24.0 with identical flags.

## Environment

- **Image**: `vault.habana.ai/gaudi-docker/1.24.1/ubuntu24.04/habanalabs/vllm-0.26.0-ptupstream-2.11.0:latest`
- **vLLM version**: v0.26.0
- **Gaudi software**: v1.24.1 (PyTorch 2.11)
- **Model**: `bottlecapai/ThinkingCap-Qwen3.6-27B-FP8` (hybrid: FullAttention + GDN layers)
- **Configuration**: TP=4, max-model-len=262144, kv-cache-dtype=fp8_inc, VLLM_SKIP_WARMUP=true, no --enforce-eager, no --speculative-config

## Reproduction

```bash
docker run -d \
  --name qwen36-fp8 \
  --runtime=habana \
  -e HABANA_VISIBLE_DEVICES=all \
  -e VLLM_SKIP_WARMUP=true \
  -v /local/hf_cache:/root/.cache/huggingface \
  --cap-add=sys_nice \
  -p 8001:8001 \
  --ipc host \
  --entrypoint bash \
  vault.habana.ai/gaudi-docker/1.24.1/ubuntu24.04/habanalabs/vllm-0.26.0-ptupstream-2.11.0:latest \
  -c 'vllm serve bottlecapai/ThinkingCap-Qwen3.6-27B-FP8 --served-model-name qwen36-fp8 --host 0.0.0.0 --port 8001 --tensor-parallel-size 4 --trust-remote-code --max-model-len 262144 --enable-auto-tool-choice --tool-call-parser qwen3_coder --reasoning-parser qwen3 --kv-cache-dtype fp8_inc --max-num-batched-tokens 8192 --max-num-seqs 256 --language-model-only'

# Wait for startup, then send a request:
curl -X POST http://localhost:8001/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{"model":"qwen36-fp8","messages":[{"role":"user","content":"Hello"}],"max_tokens":50}'
```

## Error

```
(EngineCore pid=678) ERROR 08-13 17:51:48 [core.py:1332] RuntimeError: Worker failed with error '[Rank:0] FATAL ERROR :: MODULE:PT_EAGER HabanaLaunchOpPT Run returned exception....
Graph compile failed. Recipe: .graph_dumps/graph_0019_fused_0_syn_1026000_1026000_4781, synStatus=synStatus 26 [Generic failure]. 
Last synapse error: file: recipe_manager.cpp:304 function: compileGraph, scope: SYN_RECIPE, failed condition: (ret == false), message: Can not compile graph. Recipe name .graph_dumps/graph_0019_fused_0_syn_1026000_1026000_4781, graph name: .graph_dumps/graph_0019_fused_0_syn_1026000_1026000_4781
[Rank:0] Habana exception raised from std::shared_ptr<synapse_helpers::graph::recipe_handle> synapse_helpers::graph::compile() at graph.cpp:661'
```

## Root Cause Analysis

v0.26.0 removed the `transformers==5.9.0` pin that was introduced in v0.24.0 (noted in the v0.26.0 release notes: "Restored the latest transformers version by removing the temporary transformers==5.9.0 pin introduced in v0.24.0"). The newer transformers version generates a computation graph that the Gaudi v1.24.1 Synapse compiler cannot compile for hybrid GDN models.

The v0.26.0 release notes mention "Fixed Qwen3.5 MoE post-warmup graph recompilation (#1602)", but this fix does not address the GDN hybrid model path.

## Workaround

Use v0.24.0 (`vllm-0.24.0-ptupstream-2.11.0` image) which has the `transformers==5.9.0` pin and works correctly with this model.

## Related

- #1284 — Original feature request for Qwen3.5 GDN support on Gaudi
- v0.26.0 release notes mention PR #1602 (Qwen3.5 MoE post-warmup graph recompilation fix)

**Comment by shepark** [comment]
vllm upstream, PR #50685 ( c05d75a , "Keep Qwen3Next layer boundaries sequence parallel") : the Qwen3Next/GDN sequence-parallel layer-boundary handling that was producing the malformed HPU graph error synStatus 26.
        resolution path: no vllm-gaudi code change needed, just use vllm upstream commit at/after c05d75a. Current VLLM_STABLE_COMMIT 14617c2 satisfies that.
        from vllm-gaudi commit fdd5595 (08/06).. the issue isn't shown any more as long as vllm upstream commit is higher or equal than c05d75a.
